
#数据库连接url
spring.datasource.url=jdbc:mysql://localhost:3306/test
#用户名
spring.datasource.username=root
#密码
spring.datasource.password=admin123
#数据库驱动
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml



spring.redis.database=0
spring.redis.host=127.0.0.1
#Redis服务器连接端口
spring.redis.port=6379
#Redis服务器连接密码（默认为空）
spring.redis.password=
#连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active=8
#连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1s
#连接池中的最大空闲连接
spring.redis.jedis.pool.max-idle=8
#连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=0
#连接超时时间（毫秒）
spring.redis.timeout=30000

spring.elasticsearch.rest.uris=http://localhost:9200
# 连接超时时间,单位是s
spring.elasticsearch.rest.connection-timeout=10
# 读超时时间,单位是s
spring.elasticsearch.rest.read-timeout=5
spring.elasticsearch.rest.username=alxcy
spring.elasticsearch.rest.password=alxcyliuxiaochen0712



file.hostname=49.232.77.36
file.port=21
file.user=alxcy
file.password=alxcyliuxiaochen0712
file.uploadUrl=/user-image






server.port=8712